
[options]
	#Prevents Death by Teleporting Player to Spawn if trying to enter an Ender Portal
	preventdeath = true
	#Message that displays when Teleport is blocked
	blockedmessage = "Obtain a &item% before entering %dim%"
	#Title for the Advancements
	craftedmessage = "Cinderstone"
	#Description for the Advancements
	description = "Obtain a %item% to enter %dim%"
	#Comma seperated list of items that when crafted unlock the corresponding dimension
	craftitems = "taletweaks:cinderstone"
	#Comma seperated list of Dimension Resource Names
	dimresname = "minecraft:the_nether"
	#Comma seperated list of Dimension Display Names
	dimnames = "the Nether Regions"

