
[General]
	#If true, the global volume multiplier will only be applied to affected sounds (so not to the ui sounds for example).
	"Volume Multiplier Only On Affected" = true
	#The global amount of sound reflectance energy of all blocks. Lower values result in more conservative reverb simulation with shorter reverb tails. Higher values result in more generous reverb simulation with higher reverb tails.
	#Range: 0.1 ~ 4.0
	"Global Block Reflectance" = 1.0
	#The global amount of sound that will be absorbed when traveling through blocks.
	#Range: 0.1 ~ 4.0
	"Global Block Absorption" = 1.0
	#If true, note blocks will be processed.
	"Affect Note Blocks" = true
	#The global volume multiplier of all sounds.
	#Range: 0.1 ~ 8.0
	"Global Volume Multiplier" = 4.0
	#The maximum air absorption factor when it's snowing. The real absorption factor will depend on the snow's intensity. Set to 1 or lower to disable
	#Range: 0.0 ~ 10.0
	"Max Snow Air Absorption Factor" = 5.0
	#Minecraft won't allow sounds to play past a certain distance. This parameter is a multiplier for how far away a sound source is allowed to be in order for it to actually play. Values too high can cause polyphony issues.
	#Range: 1.0 ~ 6.0
	"Sound Distance Allowance" = 4.0
	#The brightness of reverberation. Higher values result in more high frequencies in reverberation. Lower values give a more muffled sound to the reverb.
	#Range: 0.1 ~ 2.0
	"Global Reverb Brightness" = 1.0
	#The global volume of simulated reverberations.
	#Range: 0.1 ~ 2.0
	"Global Reverb Gain" = 1.0
	#The global volume multiplier of the echos, put to 0 to disable echos all together
	#Range: 0.0 ~ 2.0
	"Global Echo Multiplier" = 1.0
	#The distance under which the volume for the sound would normally drop by half (before being influenced by Attenuation Factor). 1.0 is the physically correct value.
	#Range: 0.2 ~ 2.0
	"Reference Distance" = 1.0
	#How much sound is filtered when the player is underwater. 0.0 means no filter. 1.0 means fully filtered.
	#Range: 0.0 ~ 1.0
	"Underwater Filter" = 0.8
	#Affects how quiet a sound gets based on distance. Lower values mean distant sounds are louder. 1.0 is the physically correct value.
	#Range: 0.2 ~ 1.0
	"Attenuation Factor" = 1.0
	#A value controlling the amount that air absorbs high frequencies with distance. A value of 1.0 is physically correct for air with normal humidity and temperature. Higher values mean air will absorb more high frequencies with distance. 0 disables this effect.
	#Range: 0.0 ~ 5.0
	"Air Absorption" = 1.0
	#How far the rays should be traced.
	#Range: 1.0 ~ 8192.0
	"Max Ray Distance" = 256.0

[Performance]
	#The number of rays to trace to determine reverberation for each sound source. More rays provides more consistent tracing results but takes more time to calculate. Decrease this value if you experience lag spikes when sounds play.
	#Range: 8 ~ 64
	"Environment Evaluation Rays" = 32
	#If true, enables a simpler technique for determining when the player and a sound source share airspace. Might sometimes miss recognizing shared airspace, but it's faster to calculate.
	"Simpler Shared Airspace Simulation" = false
	#If true, rain sound sources won't trace for sound occlusion. This can help performance during rain.
	"Skip Rain Occlusion Tracing" = true

["Material properties"]
	#Sound reflectivity for foliage blocks (leaves, grass, etc.).
	#Range: 0.0 ~ 1.0
	"Foliage Reflectivity" = 0.2
	#Sound reflectivity for snow blocks.
	#Range: 0.0 ~ 1.0
	"Snow Reflectivity" = 0.2
	#Sound reflectivity for wooden blocks.
	#Range: 0.0 ~ 1.0
	"Wood Reflectivity" = 0.7
	#Sound reflectivity for glass blocks.
	#Range: 0.0 ~ 1.0
	"Glass Reflectivity" = 0.5
	#Sound reflectivity for ground blocks (dirt, gravel, etc).
	#Range: 0.0 ~ 1.0
	"Ground Reflectivity" = 0.3
	#Sound reflectivity for sand blocks.
	#Range: 0.0 ~ 1.0
	"Sand Reflectivity" = 0.2
	#Sound reflectivity for slimey blocks.
	#Range: 0.0 ~ 1.0
	"Slime Reflectivity" = 0.3
	#Sound reflectivity for metal blocks.
	#Range: 0.0 ~ 1.0
	"Metal Reflectivity" = 0.97
	#Sound reflectivity for cloth blocks (carpet, wool, etc).
	#Range: 0.0 ~ 1.0
	"Cloth Reflectivity" = 0.25
	#Sound reflectivity for stone blocks.
	#Range: 0.0 ~ 1.0
	"Stone Reflectivity" = 0.95

[Compatibility]
	#REQUIRES RESTART. If true, Automatically downmix stereo sounds that are loaded to mono
	"Auto Stereo Downmix" = true

[Misc]
	#If true, Prints sound name and format of the sounds that get converted
	"Stereo downmix Logging" = false

