
[permissions]
	#Whether players can deactivate chopping e.g. by sneaking
	canChooseNotToChop = true
	#Whether this mod is enabled or not
	enabled = true

[treeDetection]
	#Whether to destroy leaves when a tree is felled
	breakLeaves = true
	#If breakLeaves is true, whether to destroy leaves that are marked as persistent when a tree is felled
	breakPersistentLeaves = true
	#The tag that blocks must have to be considered leaves (default: treechop:leaves_like)
	blockTagForDetectingLeaves = "treechop:leaves_like"
	#Maximum number of leaves blocks that can destroyed when a tree is felled
	#Range: 1 ~ 8096
	maxLeavesBlocks = 1024
	#Maximum distance from log blocks to destroy non-standard leaves blocks (e.g. mushroom caps) when felling
	#Range: 0 ~ 16
	maxBreakLeavesDistance = 7
	#Maximum number of log blocks that can be detected to belong to one tree
	#Range: 1 ~ 8096
	maxTreeBlocks = 320
	#The tag that blocks must have to be considered choppable (default: treechop:choppables)
	blockTagForDetectingLogs = "treechop:choppables"

[chopCounting]
	#Scales the number of chops (rounding down) required to fell a tree; with chopCountingMethod=LINEAR, this is exactly the number of chops per block
	#Range: 0.0 ~ 1024.0
	chopCountScale = 1.0
	#Method to use for computing the number of chops needed to fell a tree
	#Allowed Values: LINEAR, LOGARITHMIC
	chopCountingMethod = "LOGARITHMIC"

[compatibility]

	[compatibility.general]
		#Whether to prevent chopping during right-click actions; fixes a conflict with Carry On (as of carryon-1.16.3-1.15.1.7)
		preventChoppingOnRightClick = true
		#List of item registry names (mod:item) and tags (#mod:tag) for items that should not chop when used to break a log
		choppingToolsBlacklist = ["#forge:saws", "mekanism:atomic_disassembler"]
		#Whether to prevent infinite loops when chopping; fixes crashes when using modded items that break multiple blocks
		preventChopRecursion = true

	[compatibility.specific]
		#Whether to enable compatibility with ProjectMMO; for example, award XP for chopping
		projectMMO = true

