#Default setting for whether or not the user wishes to chop (can be toggled in-game)
choppingEnabled = true
#Default setting for whether or not the user wishes to fell tree when chopping (can be toggled in-game)
fellingEnabled = true
#Default setting for the effect that sneaking has on chopping (can be cycled in-game)
#Allowed Values: NONE, INVERT_CHOPPING, INVERT_FELLING
sneakBehavior = "INVERT_CHOPPING"

